spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:ticketdeskdb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# AWS Configuration (Placeholder for production)
aws.s3.bucket=${S3_BUCKET_NAME:ticketdesk-attachments}
aws.region=${AWS_REGION:us-east-1}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
server.port=9090